# Python to Excel

This project show some examples to how read and write Excel files.

Some Excel table is ready to use on directory

Use **"sheet_name="** argument to navegate between sheet tabs

In [13]:

import pandas as pd

# the table "Gastos Pessoais" has Receitas, Despesas, Investimentos, Real, Resumo e Cadastro like tabs
df = pd.read_excel("Gastos_Pessoais.xlsx", sheet_name="Receitas")

df

   Controle Financeiro Unnamed: 1  ... Unnamed: 4 Unnamed: 5
0                  NaN        NaN  ...        NaN        NaN
1   Tabela de Receitas        NaN  ...        NaN        NaN
2                  NaN        NaN  ...        NaN        NaN
3               Origem   Valor R$  ...        Mês        Ano
4              Salário       6800  ...    janeiro       2019
5                Bônus        300  ...    janeiro       2019
6      Outras receitas       1200  ...    janeiro       2019
7              Salário       6800  ...  fevereiro       2019
8                Bônus        980  ...  fevereiro       2019
9      Outras receitas       1150  ...  fevereiro       2019
10             Salário       6800  ...      março       2019
11               Bônus        320  ...      março       2019
12     Outras receitas       2200  ...      março       2019
13             Salário       6800  ...      abril       2019
14               Bônus        390  ...      abril       2019
15     Outras receitas        920  ...      abril       2019
16             Salário       6800  ...       maio       2019
17               Bônus        480  ...       maio       2019
18     Outras receitas       1240  ...       maio       2019
19             Salário       6800  ...      junho       2019
20               Bônus        670  ...      junho       2019
21     Outras receitas        980  ...      junho       2019
22               Bônus       2500  ...      junho       2019
23             Salário       6800  ...      julho       2019
24               Bônus        230  ...      julho       2019
25     Outras receitas       1390  ...      julho       2019
26             Salário       7000  ...     agosto       2019
27               Bônus        120  ...     agosto       2019
28     Outras receitas        340  ...     agosto       2019
29             Salário       7000  ...   setembro       2019
30               Bônus        220  ...   setembro       2019
31     Outras receitas       1100  ...   setembro       2019
32             Salário       7000  ...    outubro       2019
33               Bônus        320  ...    outubro       2019
34     Outras receitas        890  ...    outubro       2019
35             Salário       7200  ...   novembro       2019
36               Bônus        210  ...   novembro       2019
37     Outras receitas        970  ...   novembro       2019
38             Salário       7200  ...   dezembro       2019
39               Bônus       2500  ...   dezembro       2019
40             Salário       7200  ...    janeiro       2020
41     Outras receitas       1200  ...    janeiro       2020
42             Salário       7200  ...  fevereiro       2020
43     Outras receitas       1400  ...  fevereiro       2020
44             Salário       7200  ...      março       2020
45             Salário       7200  ...      abril       2020
46             Salário       7200  ...       maio       2020
47             Salário       7200  ...      junho       2020
48               Bônus       3100  ...      junho       2020
49             Salário       7200  ...      julho       2020
50             Salário       7300  ...     agosto       2020

[51 rows x 6 columns]

The table still not presentable to view all information, you can use **"skiprow="** argument and hide index columns number using **"index_col=False"**

In [14]:
import pandas as pd

df = pd.read_excel("Gastos_Pessoais.xlsx", sheet_name="Receitas", skiprows=4, index_col=False)

df.head(5)

            Origem  Valor R$          Destino       Data        Mês   Ano
0          Salário      6800  Banco do Brasil 2019-01-01    janeiro  2019
1            Bônus       300  Banco do Brasil 2019-01-01    janeiro  2019
2  Outras receitas      1200  Banco do Brasil 2019-01-01    janeiro  2019
3          Salário      6800  Banco do Brasil 2019-02-01  fevereiro  2019
4            Bônus       980  Banco do Brasil 2019-02-01  fevereiro  2019

Lets check out another tab on the "Gasto Pessoais" table.

In [21]:
df = pd.read_excel("Gastos_Pessoais.xlsx", sheet_name="Despesas", skiprows=4, index_col=False)

df

   Tipo de Gasto                  Detalhamento  ...      Mês   Ano
0        Moradia  Prestação /Aluguel de imóvel  ...  janeiro  2019
1    Alimentação                  Supermercado  ...  janeiro  2019
2       Educação                 Outros cursos  ...  janeiro  2019
3          Saúde                Plano de saúde  ...  janeiro  2019
4       Pessoais                    Presentes   ...  janeiro  2019
..           ...                           ...  ...      ...   ...
80    Transporte                Ônibus / Metrô  ...     maio  2020
81       Moradia  Prestação /Aluguel de imóvel  ...    junho  2020
82   Alimentação                  Supermercado  ...    junho  2020
83         Saúde                Plano de saúde  ...    junho  2020
84    Transporte                Ônibus / Metrô  ...    junho  2020

[85 rows x 7 columns]

You can also especify which columns do you want to view

In [19]:
df = pd.read_excel("Gastos_Pessoais.xlsx", sheet_name="Despesas", skiprows=4, index_col=False, usecols="A,C,F")

df

   Tipo de Gasto  Valor R$      Mês
0        Moradia      2500  janeiro
1    Alimentação      1200  janeiro
2       Educação       100  janeiro
3          Saúde      1000  janeiro
4       Pessoais      1200  janeiro
..           ...       ...      ...
80    Transporte       800     maio
81       Moradia      2900    junho
82   Alimentação      1200    junho
83         Saúde      1000    junho
84    Transporte       800    junho

[85 rows x 3 columns]

# Pandas as Context Manager

We can read file using the ExcelFile class

In [27]:
with pd.ExcelFile("Gastos_Pessoais.xlsx") as f:
    receitas = pd.read_excel(f, sheet_name="Receitas", skiprows=4, index_col=False)
    investimentos = pd.read_excel(f, sheet_name="Investimentos", skiprows=4, index_col=False)

investimentos

           Investimento  Valor R$            Fonte       Data        Mês   Ano
0            Renda Fixa      -600  Banco do Brasil 2019-06-02      junho  2019
1                 Ações      -500  Banco do Brasil 2019-06-02      junho  2019
2            Renda Fixa      -100  Banco do Brasil 2019-06-02      junho  2019
3        Tesouro Direto      -600  Banco do Brasil 2019-06-02      junho  2019
4              Poupança      -780  Banco do Brasil 2019-06-02      junho  2019
5   Previdência Privada      -100  Banco do Brasil 2019-06-02      junho  2019
6              Poupança       100  Banco do Brasil 2019-07-03      julho  2019
7            Renda Fixa       200  Banco do Brasil 2019-07-02      julho  2019
8                 Ações      -130  Banco do Brasil 2019-07-02      julho  2019
9            Renda Fixa     -5500  Banco do Brasil 2019-07-02      julho  2019
10       Tesouro Direto       200  Banco do Brasil 2019-07-02      julho  2019
11             Poupança       100  Banco do Brasil 2019-07-02      julho  2019
12  Previdência Privada      -150  Banco do Brasil 2019-07-02      julho  2019
13             Poupança     -1000  Banco do Brasil 2019-08-02     agosto  2019
14             Poupança     -2100  Banco do Brasil 2019-09-30   setembro  2019
15  Previdência Privada      -430  Banco do Brasil 2020-02-17  fevereiro  2020
16             Poupança     -4000  Banco do Brasil 2020-04-27      abril  2020

# Openpyxl Package

Now we're going write a table using the Openpyxl package

In [28]:
import openpyxl
from openpyxl.worksheet.table import Table, TableStyleInfo

workstation = openpyxl.Workbook()

sheet = workstation.active


grade = [
    ['Math', 'Monday', '2 hour', 'Celine', 'On-line'],
    ['Programming', 'Friday', '1 hour', 'Robert', 'On-site'],
    ['Science', 'Tuesday', '3 hour', 'Jack', 'On-line'],
    ['Physics', 'Wednesday', '1 hour', 'Paul', 'On-site'],
]

sheet.append(["Lesson", "Day", "Duration", "Teacher", "Local"])
for row in grade:
    sheet.append(row)

table = Table(displayName="Grade-lesson", ref="A1:E5")

style = TableStyleInfo(name="TableStyleMedium9", showFirstColumn=False,
                       showLastColumn=False, showRowStripes=True, showColumnStripes=True)

table.tableStyleInfo = style

sheet.add_table(table)
workstation.save("grade_lesson.xlsx")

Lets check the new table "grade_lesson"

In [29]:
lesson = pd.read_excel("grade_lesson.xlsx")

lesson

        Lesson        Day Duration Teacher    Local
0         Math     Monday   2 hour  Celine  On-line
1  Programming     Friday   1 hour  Robert  On-site
2      Science    Tuesday   3 hour    Jack  On-line
3      Physics  Wednesday   1 hour    Paul  On-site